# Sample deployment for memory-intensive workloads (targets r8g/x8g instances)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive-app
  labels:
    app: memory-intensive-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-intensive-app
  template:
    metadata:
      labels:
        app: memory-intensive-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64  # For Graviton instances (r8g, x8g)
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: 16Gi  # High memory request will favor r8g/x8g instances
            cpu: 2
          limits:
            memory: 24Gi
            cpu: 4
        # Redis configuration for memory-intensive workload
        args:
        - "--maxmemory"
        - "20gb"
        - "--maxmemory-policy"
        - "allkeys-lru" 