# Sample deployment with specific instance type requirements
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-compute-optimized
  labels:
    app: nginx-compute-optimized
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-compute-optimized
  template:
    metadata:
      labels:
        app: nginx-compute-optimized
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: c5.medium
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi 