# Sample deployment for Spot instances (x86)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spot-x86
  labels:
    app: nginx-spot-x86
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-spot-x86
  template:
    metadata:
      labels:
        app: nginx-spot-x86
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        karpenter.sh/capacity-type: spot
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi 